models:
  - name: Qwen3.5-397B-A17B
    model_path: /mnt/models/Qwen_Qwen3.5-397B-A17Bd
    gpus: 8
    tensor_parallel_size: 8
    gpu_memory_utilization: 0.95
    extra_args: ""
    reasoning_parser: qwen3
    tool_args: "--enable-auto-tool-choice --tool-call-parser qwen3_coder"
    venv_activate: /root/vllm-nightly-16022026/.venv/bin/activate
    notes: "Example from Fabian"
  - name: GLM-4.6V-FP8
    model_path: /mnt/models/zai-org_GLM-4.6V-FP8
    gpus: 1
    tensor_parallel_size: 1
    gpu_memory_utilization: 0.95
    extra_args: "--trust-remote-code --max-model-len=120000 --structured-outputs-config.backend xgrammar --structured-outputs-config.disable_any_whitespace true --attention-config.backend FLASHINFER --mm-encoder-tp-mode data --mm-processor-cache-type shm"
    reasoning_parser: glm45
    tool_args: "--enable-auto-tool-choice --tool-call-parser glm45"
    venv_activate: /root/vllm-0.15.0-transformers5/.venv/bin/activate
    notes: "Vision model with xgrammar and FLASHINFER attention"
  - name: Qwen3-0.6B-FP8
    model_path: Qwen/Qwen3-0.6B-FP8
    gpus: 1
    tensor_parallel_size: 1
    gpu_memory_utilization: 0.03
    reasoning_parser: deepseek_r1
    extra_args: "--max-num-seqs 10 --enforce-eager --max-model-len 2048"
    venv_activate: /root/vllm-nightly-16022026/.venv/bin/activate
    notes: "small model"
