models:
  - name: Qwen3.5-397B-A17B
    model_path: /mnt/models/Qwen_Qwen3.5-397B-A17Bd
    gpus: 8
    tensor_parallel_size: 8
    gpu_memory_utilization: 0.95
    extra_args: ""
    reasoning_parser: qwen3
    tool_args: "--enable-auto-tool-choice --tool-call-parser qwen3_coder"
    venv_activate: /root/vllm-nightly-16022026/.venv/bin/activate
    notes: "Example from Fabian"
